modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://rr-dev.atlassian.net/servicedesk/customer/portal/3"
[[mods]]
modId="albedo"
version="${file.jarVersion}"
displayName="Albedo"
credits="Tewan (1.14 Port)"
authors="Horizon Studio, Elucent"
description='''

'''